# `PuLPException` exception

::: pyorlib.exceptions.PuLPException

<br>